### ISSUE TITLE
fbgate interaction dont work.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#101]
Impossible enter on fbgate furnis.

**Comment by ovflowd** [comment]
Can  you post a screenie please?

**Comment by Anthologique** [comment]
Edit: Works Fine.

**Comment by ghost** [comment]
Impossible enter on fbgate furniture.
I think no bad coded, just packet error.
Video: http://tinypic.com/player.php?v=2wpo58o%3E&s=9#.V5syjxWLS70

**Comment by ovflowd** [comment]
Did you tried click directly in the gate?

**Comment by ghost** [comment]
Yes, and dont work ^^.

**Comment by ovflowd** [comment]
Sad. We will try to fix it in `LINUX` branch Release's. But, we are currently busy by rewriting the entirely Emulator..
