### ISSUE TITLE
Room with groups dont appear on navigator.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#102]
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15625973/2f30a918-24b9-11e6-875d-d02d16fd602b.png)

**Comment by ovflowd** [comment]
That's weird. But as i said, please stop creating new issues. These issues are from `NIO` branch. And we're not giving support in NIO branch.

**Comment by ghost** [comment]
Close this issue.  
Work fine.
