### ISSUE TITLE
Furnidata Error

### ISSUE THREAD

**Issue by UzielBalderas** [sant0ro/Yupi#107]
help .. No loading furnis in yupi emulator.. i use swf's habboon edit.. how you can furnidata.xml?? our catalogue page with drc's

http://prnt.sc/bx41w8
http://prnt.sc/bx41tj

**Comment by ghost** [comment]
Download last furnidata off habbo.com and works ;).

**Comment by ovflowd** [comment]
Exactly as @Anthologique said.

**Comment by UzielBalderas** [comment]
now the users entering his room, the client reload...
