### ISSUE TITLE
2 problems.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#109]
Problem n°1:
When i click on "Change my name" and "Ok" button, i received a disconnect of client.

Problem n°2:
The online badge stop work after level 5.

Screenshot:
![sans titre](https://cloud.githubusercontent.com/assets/6734589/17217134/91677a26-54e3-11e6-899a-f15b9c19c5f8.png)

**Comment by TheDoct0r11** [comment]
1. Probably invalid packet structure. Will investigate once linux is done.
2. Will need to investigate... But that's odd...

**Comment by ovflowd** [comment]
1. Don't need investigate. That code was removed from Yupi, since isn't unsafe and not used anymore by Habbo.

**Comment by TheDoct0r11** [comment]
It's not an safety issue, but rather an issue of bad database design.
Pretty much every emulator tends to copy the usernames around everywhere instead of simply using the user id...

**Comment by ovflowd** [comment]
Yupi uses user id. I Already changed that. The security issue is around the input of the username choose.
