### ISSUE TITLE
New Problem

### ISSUE THREAD

**Issue by HotelXz** [sant0ro/Yupi#11]
Hi, i have tried your emulator (yupi), i saw a huge problem, i cant login after i have created a room, I cant load the room in the navigator and go to a room the screen is just black and i get massive errors, Here u got the error log hope u can fix it thanks: http://pastebin.com/HsRNWM0y

**Comment by HotelXz** [comment]
i dont know if this is a working or a just beta, but i didnt get up the items in the catalog pages when click it thanks for this

**Comment by sant0ro** [comment]
Remembering. This is a Pre-Release. The emulator isn't finished for production usages.
Soo these bugs of casting are totally normal. When the 1.0 release (beta) be released. Will be able to production usages. 

The actually builds are pre-beta, and pre-alpha.
Cheeers,
