### ISSUE TITLE
Problem with groups.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#110]
When i create a new group, i received a new pending request with my name...
Screenshots:
![2](https://cloud.githubusercontent.com/assets/6734589/17217365/662f3546-54e4-11e6-967d-4706f9b0851b.png)
![sans titre](https://cloud.githubusercontent.com/assets/6734589/17217366/66382552-54e4-11e6-8f36-2490bfa26ea8.png)

**Comment by ovflowd** [comment]
Yes this is a very weird bug, i really don't know why this happens.
But is `NIO` branch so..
