### ISSUE TITLE
Problem with wireds bots.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#112]
Look screenshot:
![sans titre](https://cloud.githubusercontent.com/assets/6734589/17217746/ba687400-54e5-11e6-925b-c720726fe318.png)
Important: (I have add all furniture interactor).

**Comment by ovflowd** [comment]
Check the interaction_type at Database.

**Comment by ghost** [comment]
All interaction type its good for all wired furniture.
Dont work.
