### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by ovflowd** [sant0ro/Yupi#116]
![image](https://cloud.githubusercontent.com/assets/12037269/17253115/b1e5542e-5585-11e6-8c73-218f3926322f.png)
That was an idea of a good developer from RaGEZONE Martinmine, what you think @TheDoct0r11 , we will change to .NET Core, after refactorement?

**Comment by TheDoct0r11** [comment]
Just had to read up on .Net Core. Basically that looks like a good idea.
But we will have to check weather the libraries we're using are supporting .NET Core...
Also before switching to .NET Core I'd rather  want to do some extensive testing and if someone is motivated enough create some unit tests (NUnit)

Keeping this open as a reminder.

**Comment by Anthologique** [comment]
@sant0ro Are you ideas for i download all habbo furniture ? (Le contain of "hof_furni" folder on Habbo.com)

**Comment by sant0ro** [comment]
Sory @Anthologique what are you talking about?

**Comment by Anthologique** [comment]
I will all furniture off Habbo.com, how i dowload the latest "hof_furni" folder please ?

**Comment by ovflowd** [comment]
@Anthologique please stop posting spam. This issue isn't related to furniture. But to .NET Core
Locking conversation.
