### ISSUE TITLE
Problem with Bots and Pets.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#122]
Bots and Pets dont will say.

**Comment by ovflowd** [comment]
Yes i know why. I will commit the fix.

**Comment by ghost** [comment]
Okey :)

**Comment by ovflowd** [comment]
Fixed in last commit.
Download last commit and build emulator.

**Comment by ghost** [comment]
I use the latest version (Yupi 1.1.1) THIS DAY and dont work.

**Comment by ovflowd** [comment]
I said to download last commit, not last release. You need understand differences between commits and releases.

**Comment by ghost** [comment]
--'
I use the latest https://github.com/sant0ro/Yupi/tree/nio version
DONT WORK.
