### ISSUE TITLE
Problem with rooms config 2/2.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#125]
Bug n°1:This option dont work.
Bug n°2: Wheni check the case, and i reconnect on the client, the case is unchecked.
![2](https://cloud.githubusercontent.com/assets/6734589/17278833/c58c53c8-5766-11e6-833f-74bc7bd36992.png)

**Comment by TheDoct0r11** [comment]
See https://github.com/sant0ro/Yupi/issues/124#issuecomment-236458549
