### ISSUE TITLE
In-Game: Can't buy gift

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/Yupi#15]
When you click to buy gift, you receive a beautifull disconnect from game, without errors in emulator.
Probably: Wrong Packet, or Wrong code in PurchaseHandler

**Comment by bblackv** [comment]
packet wong

**Comment by sant0ro** [comment]
Thanks! If you can, can send me the error when try to buy gift? Also can you tell to me if is the incoming or outgoing wrong?

What happens when try to buy gift? Disconnect yeah? So i think exists two possibles:
1. Wrong packet structure
2. Wrong packet

Since AHPU is 90% reliable, so is possible the item 2 as is possible the item 1.

Thanks!

**Comment by bblackv** [comment]
outgoing wrong

ps: It's good to review the outgoing

**Comment by sant0ro** [comment]
Okay!
