### ISSUE TITLE
Groups Issues

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/Yupi#21]
> If you're admin from the group, and leave. Your admin status continue since the emulator restarts.
> Now you can give admin to a group member after he enter in the group without needing of restart emulator (fixed)
> Ejectall commands doesn't work (isn't coded)
> Pickall doesn't work for Group Admins
> Group Owner appears as Pending Member

Group Admins or Members with rights, can only remove theirs items (fixed)
Group Forums Report Thread doesn't work (not coded packet)

**Comment by HotelXz** [comment]
Bug update: If u create a group and look at the group info it says that im as owner are pending on invite for go in the guild thanks

**Comment by sant0ro** [comment]
Please, repeat what you're saying i didn't understand.

Yeah the owner stay as pending, only disappear after restart emulator. But owner still owner.

**Comment by HotelXz** [comment]
Yeah that with pending owner dissapear but here is the logg for delete the group: http://pastebin.com/SS2aNzNY

thanks for the good work

**Comment by sant0ro** [comment]
You need download last version --'.

**Comment by sant0ro** [comment]
Closed, Referenced.
