### ISSUE TITLE
Mod Tools Issues

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/Yupi#23]
1. Only can send Intimidates Tickets, other tickets you cannot send.. (why?)
2. You can send other ticket types only if the user of the room isn't admin, or room owner.
3. When you try open a ticket with other opened, a window asking if want to release the oldest open. But if you click release, nothing happens. Also this window only appear for intimidate tickets.
4. In the mod tools, some description doesn't appear for intimidate tickets

**Comment by HotelXz** [comment]
Bug update for u: Chatlog dosent save in the chatlog window if u use unload or reload command, Same if u click user info -> room chat, the chat of the player isnt there, Thanks for this good updates bro

**Comment by sant0ro** [comment]
The chatlog saves. Immediately after you type the message. Is absolutely normal this.
But the chatlog disappears after room unload? this doesn't make any sense. I will check..

**Comment by HotelXz** [comment]
the chatlog dont saves, its the problem thanks.

**Comment by sant0ro** [comment]
@trylix
