### ISSUE TITLE
Bot Issue

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/Yupi#24]
1. The bot doesn't go to you when he give something to you. In habbo he need go to you. (Isn't coded in Yupi)

**Comment by HotelXz** [comment]
I want to give u one more bug with the bot, If u got 1 or more bots in your room and use the floorplan maker and change the floor and reenter the room u cant walk or the items and the bot are gone in the room, Proof: https://gyazo.com/e22228abfbdd396ab345df49213b95a1

**Comment by sant0ro** [comment]
This doesn't make any sense. Please check for Exceptions log...

**Comment by HotelXz** [comment]
Sorry for slow replay but here is the exceptions log: http://pastebin.com/XQPwCYrh

**Comment by sant0ro** [comment]
Please. Use last version.

**Comment by HotelXz** [comment]
I use the last one?, i get the errors with the last commit emu?

**Comment by sant0ro** [comment]
Please. When update the database. You need delete the entire database. Because the Foreign Keys.
Please don't use last release. Build yourself the emulator.

This bug doesn't exists. But I will check. And isn't because of two bots.
Please here is a place to post valid issues, based in logs. Or based in screenies. If this bug exists, please post logs from emulator, or screenies.

**Comment by Proinesis** [comment]
[ExceptionsLog.txt](https://github.com/sant0ro/Yupi/files/75191/ExceptionsLog.txt)

**Comment by sant0ro** [comment]
Fixed Bots Errors.
