### ISSUE TITLE
Game: Wireds Issue List Reporting

### ISSUE THREAD

**Issue by Arfeu** [sant0ro/Yupi#25]
# Wireds Issues
**This Issue List is for Reporting Every Wired Configuration / Execution / Issues / Delays**

### Description
Wired Items Change Logs will be reported in _Development Acomplish_

### Assigned
For Everyone

### Development Acomplish
Referenced in #5

**Comment by sant0ro** [comment]
I will check that. Probably something misconfigured. Or the emulator think the item unique I'd is the same.

**Comment by sant0ro** [comment]
The of functions conflict when has more than one in the bedroom

First in operation
https://gyazo.com/04332b5c1d3f2f6cecf746d5a6cabfad

Second in operation
https://gyazo.com/9fbaa11ec4ece720adf14d5d47bf0abf

Note what the condition selected the green module for have control from below however it interferes with the side
https://gyazo.com/9f8b4191e4a7e6b4bd719b887d3665ba
