### ISSUE TITLE
Clothes do not carry

### ISSUE THREAD

**Issue by FatalytRap** [sant0ro/Yupi#26]
The clothes of my hotel are not charging, already changed my SWF several times and have checked several times if the wrong configuration. I do not know what else to do.
I will post some of my prints SWF I was using with Azure 2.0 and everything was working 100%, I've changed the Habbo.swf.

http://imgur.com/a/gEggN

All commands work, mobs, etc ... LESS visual, they do not carry.
I am eager to use the emulator of you, and I'm desperate because I can not put these visuals to work. PLEASE HELP ME.

**Comment by sant0ro** [comment]
You know that this new release, has two extra .xml, the PRODUCTION has more xml's on gordon. Check for some 404 not found in the client.

**Comment by FatalytRap** [comment]
Is there any own swf for this emulator?
