### ISSUE TITLE
Yupi Database doesent work with OneCMS v4

### ISSUE THREAD

**Issue by KilluaKira** [sant0ro/Yupi#27]
do you think to adapt database to one cms v4? sorry for my english i'm italian and i like this emulator
thanks in advance

**Comment by sant0ro** [comment]
No.

**Comment by sant0ro** [comment]
Observation: It's in development this emulator. Not for Production usage.

Cheers
;)

**Comment by KilluaKira** [comment]
of course I know it's in development but I wish I could give it a try

**Comment by KilluaKira** [comment]
@sant0ro If you would like to see the site where I would give it a try here is the url www.sunakehotel.com i use azure 1.190, because unfortunately I don't find what I need and the 2100 and 2200 of azure have many bugs being betas

**Comment by KilluaKira** [comment]
If you want to visit my website here is the url www.sunakehotel.com
