### ISSUE TITLE
Error Ticket

### ISSUE THREAD

**Issue by DJGOMEZV** [sant0ro/Yupi#29]
Is My Error in Yupi:

System.InvalidCastException: La conversi?n especificada no es v?lida.
   en Yupi.Game.Users.Factories.UserDataFactory.GetUserData(String sessionTicket, UInt32& errorCode)

**Comment by sant0ro** [comment]
Fixed.

**Comment by DJGOMEZV** [comment]
I still keeps coming this error:

Bug During user login: System.InvalidCastException: The conversion is not specified v n Lida?.
    in Yupi.Game.Users.Factories.UserDataFactory.GetUserData (sessionTicket String, UInt32 & errorCode)
    in Yupi.Game.GameClients.Interfaces.GameClient.TryLogin (String AuthTicket)
