### ISSUE TITLE
Follow the same mistake and you lower the new source (Error Ticket)

### ISSUE THREAD

**Issue by DJGOMEZV** [sant0ro/Yupi#30]
I still keeps coming this error:

Bug During user login: System.InvalidCastException: The conversion is not specified v n Lida?.
    in Yupi.Game.Users.Factories.UserDataFactory.GetUserData (sessionTicket String, UInt32 & errorCode)
    in Yupi.Game.GameClients.Interfaces.GameClient.TryLogin (String AuthTicket)

**Comment by sant0ro** [comment]
I tested in many computers. And I didn't get that error. Are you using the included database? Which version of MySQL? Is your client sending an so ticket? Maybe your SSO field in database or client is empty, so he can't do a casting with empty data.
Null is considered empty data, in the database empty column auth_ticket or client with empty sso_ticket is considered empty data, and null has no conversion.

**Comment by DJGOMEZV** [comment]
The customer has sso.ticket running, sends the generated ticket to the database and always has, it is rare that I do this, I have PHP MySQL 5.6.12 and 5.0.11

**Comment by sant0ro** [comment]
Sorry, but this error doesn`t happens here. I can`t reproduce the issue.
