### ISSUE TITLE
InvalidCastException on database values

### ISSUE THREAD

**Issue by Yannici** [sant0ro/Yupi#31]
Hi @sant0ro,

I'm not new to programming, but this is strange:
I wanted to add some code, so the emulator can work with my database structure, but I have some problems with casting the datarow-objects. When the code has to execute something like `(int)dataRow["column"]`, I get an InvalidCastException. The value in the database is (of course) an integer! Could you please tell me why this is happen? In other emulators I work, this is working perfectly.

At the moment I have to fix all code like above to `Convert.ToInt32()`, and then it's working perfectly.

Thanks in advance!

**Comment by sant0ro** [comment]
Hello, first the column can be an INTEGER, but isn't totally a clean-integer type, check if this field is PRIMARY, or an INDEX or is UNSIGNED, or is tinyint, or has some attributes.

If has UNSIGNED is an (uint)
if has other properties is better using int.Parse() (that will convert the object to integer)

**Comment by Yannici** [comment]
Even on database-tables copied from your Database.sql it isn't working. For example the field `id` of table `users` is an primary key, unsigned int and following code doesn't work: `(uint)dRow["id"]`. Maybe there are some restriction in the build configuration? I already checked that, but found nothing.

**Comment by sant0ro** [comment]
Exactly, because the field ID from users is an INDEX, particularly a PRIMARY KEY.

**Comment by sant0ro** [comment]
In these cases you ned put Convert. or int.Parse

**Comment by Yannici** [comment]
And why this is working with your database <-> code? Because you're using direct-cast `(uint)`, too. For example for field `credits` unsigned int, no index, the code `(uint)dRow["credits"]` doesn't work ...

**Comment by Yannici** [comment]
Ok, finally, it's working like you said. I'm sorry ;-)

**Comment by sant0ro** [comment]
;)
