### ISSUE TITLE
Ticket Still mistake, please help me

### ISSUE THREAD

**Issue by DJGOMEZV** [sant0ro/Yupi#32]
Me this error is still out, because you can not help me?

Bug during user login: System.InvalidCastException: La conversi?n especificada no es v?lida.
   en Yupi.Game.Users.Factories.UserDataFactory.GetUserData(String sessionTicket, UInt32& errorCode)
   en Yupi.Game.GameClients.Interfaces.GameClient.TryLogin(String authTicket)

**Comment by sant0ro** [comment]
@DJGOMEZV i can't do anything about this if i can't REPRODUCE the error. How i will fix a error that doesn't happens with me?

**Comment by DJGOMEZV** [comment]
He used iSummerCMS property and works in Azure Emulator ticket, I have the ticket that is generated or have to put one in particular, or as you access your server? I could spend the ticket generator of your CMS?

**Comment by sant0ro** [comment]
Hum.. i really don't know why is this happening DJ, but will search.

**Comment by sant0ro** [comment]
Closed.
