### ISSUE TITLE
List of bugs

### ISSUE THREAD

**Issue by dm5wg** [sant0ro/Yupi#37]
- Trade in game is not working (Now you can put the item but not trade, says that trade is not active with email)
- Gifts not working (Client Crash)

**Comment by PeDrOxRD** [comment]
Every time you press offer when you trading the emu give you a incoming 282 refused packet

**Comment by PeDrOxRD** [comment]
I've been trying to make it work , but i dont get it , it just don't get the packet and dont process this function OfferTradeItem(GameClientMessageHandler handler),i don't know what else to try

**Comment by PeDrOxRD** [comment]
found the problem, change the packet ID from 2354 to 282 Good night !

**Comment by dm5wg** [comment]
Thanks Pedro!

**Comment by PeDrOxRD** [comment]
I've been looking for it , but i don't understand why is giving me that message, I'll try to find out

**Comment by dm5wg** [comment]
Same

**Comment by dm5wg** [comment]
Thanks sant0ro!

**Comment by PeDrOxRD** [comment]
Did anyone found out yet about the other problem ?

**Comment by sant0ro** [comment]
I will continue working in Yupi tomorrow. I will search this bug.
