### ISSUE TITLE
Problem with connection

### ISSUE THREAD

**Issue by dm5wg** [sant0ro/Yupi#41]
![image](https://cloud.githubusercontent.com/assets/16397685/12387840/87f23dce-bdcf-11e5-8b85-8de3400e2e1e.png)

I have this error after few hours. It says is 1 connection and no users online, and when user connect server kicks him saying isn't online.

Close never success.

**Comment by sant0ro** [comment]
Conflict in Connections. do the following:
Open: Yupi/Data/ServerCPULowPriorityWorker.cs

Comment these lines:
```
if (realOnlineClientCount != clientCount)
                        Writer.WriteLine("Number of Clients isn't Equal of Online Users. Running Analysis", "Yupi.Game",
                            ConsoleColor.DarkYellow);

                    if (realOnlineClientCount != clientCount)
                        Yupi.GetGame().GetClientManager().RemoveNotOnlineUsers();
```

**Comment by dm5wg** [comment]
Thanks, it works!

**Comment by dm5wg** [comment]
After few hours I'm still having troubles.

![image](https://cloud.githubusercontent.com/assets/16397685/12433908/f31a5a8e-bf03-11e5-8c6f-123362feee42.png)
