### ISSUE TITLE
New Bug List

### ISSUE THREAD

**Issue by KubboSO** [sant0ro/Yupi#43]
- The command : refresh_catalogue
- " Buy as a gift " in the catalog
- Battle Banzai is not working properly
- Football is not working properly
- Skateboarding is not working

- Were bought with " Limited Edition " in the catalog Rare since not counted , for example, the number 10 other sold Number : 10

- The Limited Edition furniture there following error : https://gyazo.com/f03ed36d19150badf1704ce9cb21573f

**Comment by sant0ro** [comment]
Going to see these bugs.

**Comment by sant0ro** [comment]
Please don't Caps.

**Comment by KubboSO** [comment]
I find the emulator very great, only the problem is the existence of these few bugs yet

**Comment by dm5wg** [comment]
After few hours I have this:

![image](https://cloud.githubusercontent.com/assets/16397685/12434232/c6f7d240-bf05-11e5-9e4f-4060a837983e.png)

**Comment by ImNotSatan** [comment]
@dm5wg not just you
