### ISSUE TITLE
[Request] (not an issue) Wordfilter Rewrite/Improve

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#44]
I would like to see the word filter like phoenix:

For example, i tink the IDs in the blackword table are unneeded, and wold love to see a replacement table

**Comment by sant0ro** [comment]
Sorry i didn't understood. Explain better

**Comment by ImNotSatan** [comment]
Yupi has

If you saw a word in the blackwordfilter

It always changed to bobba

Phoenix has

replacement per word wich is quite sweet

**Comment by sant0ro** [comment]
Change in wordfilter.ini ...

**Comment by ImNotSatan** [comment]
No i ment like, replacemet for each word

A diffrent replacement per word

**Comment by sant0ro** [comment]
That is exactly what i said --'
