### ISSUE TITLE
Yupi Emulator: Main Issue Reporting List

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/Yupi#47]
# Main Issues List.
- **Described in Answers.**
- **Referenced More Details in First Answer**

## Refencing Collaborators:
- @trylix 
- @BurakDev 
- @Rockster34 
- @SirJamal 
- @iamdroppy 
- @CineXMike

**Comment by sant0ro** [comment]
#43

**Comment by dm5wg** [comment]
Nice!

**Comment by ovflowd** [comment]
**Referenced Issues**
1. Referenced #48 Rights Order Wrong
2. Referenced #22 Helper Tools List
3. Referenced #50 Small Bug List
4. Referenced #53 Pets Bugs
5. Referenced #43 New Bug List
6. Referenced #37 List of Bugs 
7. Referenced #46 Trading Bugs
8. Referenced #42 Bots Handitem FIXED
9. Referenced #15 Can't buy gift
10. Referenced #22 Helper Tools Issues
11. Referenced #52 Some Small Bugs
12. Referenced #12 Guardians
13. Referenced #23 Mod Tools Issues
14. Referenced #21 Groups Issues
15. Referenced #1 Rewrite Catalogue

**Comment by sant0ro** [comment]
Issued: refresh_catalogue isn't sending outgoing message composer. But if you give f5 you will see new catalogue, also restart works for everyone see new catalogue.
Observation: I will fix why isn't sending outgoing composer.

**Comment by sant0ro** [comment]
Issued: Some Times Room's Threads Crashes Inexperatelly making the Room Unloads and appears with 0 users. You can enter but not move, only teleport. That gives Exception. After restarting everything appears normal.
Observation: Will try to search from where is.

**Comment by sant0ro** [comment]
**Issued**: Some times when try shutdown/restart freezes in Saving Inventary Content
**What i think is**: Some Foreign Key didn't allowing Update Data.
**Which i think is**: Or pets, or group or bots data. 
**How to reproduce**: Try enter in a room with pets or bots or groups, change some data like wait the bot or pet walk or change some group data. If when you try restart freezes, maybe is that. To confirm, force restart. And use normally rooms without bots, pets, or groups. And don't enter in rooms with that, and don't buy these items. If doesn't freeze the bug is that. 
**Refine**: See what is: Group or Pet or Bot
**Observation**: I will try to fix that.

**Comment by sant0ro** [comment]
**Issued**: Limited Edition Doesn't Count Down
**Informations**: Appearly when you update Limited Edition furni state the Image of LTD disappears and also Doesn't count down when buy LTD.
What i think is: Maybe the Emulator isn't storing that the item is LTD, so when exists Item Update the LTD disappear. And countdown doesn't exists.
**Weird**: LTD Appears in Inventory and After Placing, maybe the Query to Update Items isn't adding LTD param, so the LTD fact is being ignored. Also the reason of LTD countdown probably is not executed query.
**Observation**: Will try to reproduce and fix it.

**Comment by sant0ro** [comment]
**Issued**: Trading doesn't work.
**Images**: I saw the Trading box with Illumina Design.
**I'm lazy**: Does the trade box design changed?
**What can be**: I really don't know if structure is outdated or wrong. But appears message saying the User Isn't able to Trade. Mail confirmation? Packet for NUX user?
**Observation**: Will try to reproduce and fix it.

**Comment by sant0ro** [comment]
**Issued**: #15 Gift Problem. Reason: Unknown
**What i will do**: First check the other bugs, and after that will check that
**What i think is**: Wrong code, or Outdated Packet Structure, or wrong query. I din't checked already that.
**Observation**: This is not priority now, first fix other things. But i will fix this.

**Comment by sant0ro** [comment]
**Issued**: Sometimes freezes as 76% when try to Login
**Probably Reason**: When you Add Youtube Videos
**Observation**: Will try to fix this too

**Comment by sant0ro** [comment]
**Issued**: If you increase highly your MySQL Spool, sometimes depending your MySQL configuration will give "Too Many Connections". As the Yupi doesn't uses Persistente Connections, Data will be lost.
**How to Fix**: Decrease your "db.pool.maxsize" on Main.ini
**Observation**: I will commit with a really low value. You can change it at your risk.

**Comment by sant0ro** [comment]
**Issued**: Maybe Yupi isn't closing Connections of MySQL, that makes the Pool Increase Highly, and when reach the max can't continue.
**What can be**: Probably wrong code in Yupi
**Observation**: I will try to fix it.

**Comment by sant0ro** [comment]
**Issued: Create Ticket Issues
**Problems**:
+ When click Intimidate Reasons automatically send without selecting the user. That makes a little weird bug.
+ Only can select Intimidate, other Reporting doesn't work
**What can be**: Maybe isn't coded, or coded not properly.
**Observation**: Will try to fix it.

**Comment by sant0ro** [comment]
Referenced #23

**Comment by sant0ro** [comment]
Removed answers from Fixed Items.
Updated Issue 
Updated Answers with probably fixed.

**Comment by sant0ro** [comment]
**Issued**: Proxy doesn't work
**Reason why**: CrossDomain Policy doesn't uses Proxy Port.
**Observation**: Will try to fix this.

**Comment by sant0ro** [comment]
**Issues**: Room Promotions make you freeze (in emulator leave) the room.
**What happens**: The Room Promotion buys 100% after reentering room the promotion appears. 
**Problem**: Probably wrong structure, but don't sure, generally when is you receive Hotel DC and not Room Freezing.
**Observation**: Will try to fix.

**Comment by ImNotSatan** [comment]
Shutdown issue still occurs

**Comment by sant0ro** [comment]
**Issued**: Sometimes the Reusable MySQL Connection try to use a Connection that is already being used.
**How to fix it:** Making a check if the Connection has already a DataReader (that means if is already executing some procedures) And use other that isnt.
**Observation**: Will try to fix it.

**Comment by sant0ro** [comment]
**Issued**: Can't dismount from Horse Saddle
**Issued**: You can remove saddle while mounting.
**Issued**: Only say from the room if you pickup.
**Reason**: Pets aren't coded totally, need to finish coding and rewriting
**Observation**: Pets isn't done, i will code this/fix this, but isn't totally major now.

**Comment by sant0ro** [comment]
**Issued**: Baby Pets Bad Coded
**Sub-Issued**: baby pets aren't really coded, onliest way is using a pet breed tool, but pet breed tools doesn't working properly
**Sub-Issued**: Pet Breeding doesn't works.
**Reason**: Pet Breeding is bad coded and doesn't finished code, also baby pets aren't coded. The way that are implemented is really bad.

**Comment by sant0ro** [comment]
**Issued**: Mod Tools Problems
**Problems**:
- Can only do Bullying Report (First Option - Automatic)
- Automatic Reporting doesn't able you to select the reported user, weirdly when you select a user to report this user need to be selected, but the box with select user appears as same time with the sucessfull report sent box.
- Can't do other reports
- Default Message Presets aren't coded, that makes a blank box appear when you do default actions like Close as Resolved, Close as Useless, etc.
- When your ticket isn't closed, when you choose to trash the ticket to create another the ticket isn't trashed and can't create other ticket
- Other problems?
**Reason**: Bad Coded, don't totally coded
**Observation**: Will try to fix it, first major items.

**Comment by sant0ro** [comment]
**Issued**: Guardians System Doesn't Work
**Reason**: Aren't coded
**Observation**: Will try to fix it.

**Comment by sant0ro** [comment]
**Issued**: Builders Club Problems
**Problems**:
- When you pickup item doesn't remove from count used items
- Message after 60 minutes :_Isn't really a bug, you only need change max time, change to high value._

**Comment by sant0ro** [comment]
**Issued**: Home Room
**Problem**: Can't set Home Room
**Observation**: Will try fix it.

**Comment by sant0ro** [comment]
**Issued**: Groups Issues
**Problems**:
- After creating room you stay as pending
- Option for delete group appears for everyone (or only staffs??)
- When try to delete group says the group has not room, but if you enter in the room you can delete it, after deleting it the group continue appearing in your profile, only after restart disappears (or after reenter hotel for you??)
**Observation**: Will try to fix it.

**Comment by sant0ro** [comment]
**Satan**: Inventary is saved but can't go out from Saving Inventary Content Loop.
WHYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

**Comment by ovflowd** [comment]
@TheDoct0r11 this list need be updated.
