### ISSUE TITLE
Rights order wrong

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#48]
For some reason if you select someone>actions>

It always starts at: Remove Rights

so if you want to give rights you have to click Remove Rights, and then Give Rights again for some reason.

**Comment by sant0ro** [comment]
Rooms or Groups?

**Comment by ImNotSatan** [comment]
Rooms

**Comment by sant0ro** [comment]
Will check it after my exam.

**Comment by ImNotSatan** [comment]
Aye mate gl @ ur exam
