### ISSUE TITLE
Wired interactiontypes not correct

### ISSUE THREAD

**Issue by jordynegen11** [sant0ro/Yupi#49]
Please update the SQL with an updated catalog

**Comment by sant0ro** [comment]
The Catalog is Third Party and under Development.
Someone can do that if want.

**Comment by jordynegen11** [comment]
How do you test your Wired then?

**Comment by sant0ro** [comment]
pixarhotel.com.br We changing and updating catalog and interaction types.

**Comment by jordynegen11** [comment]
Ah okey, and can you be so nice to give us the catalog_funitures and catalog_items of the wired?

**Comment by sant0ro** [comment]
The catalog isn't done, we writing it. 40% done. Is hard to create a totally correct catalog. With all correct interactions :/

**Comment by jordynegen11** [comment]
Okey, np we wait.

**Comment by sant0ro** [comment]
Closed because is not an issue. Only catalog with wrong interaction_types setted. 

**How to fix**: I'm working in a good catalogue for Yupi.
