### ISSUE TITLE
Small bug list

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#50]
- Fastwalk is not coded

- Onewaydoors verry buggy, if you use one at the end of the room you get stuck/room craches

**Comment by ImNotSatan** [comment]
Stacking tile also does not work properly i tink

**Comment by ImNotSatan** [comment]
catalog_furnitures: enableid not working

**Comment by sant0ro** [comment]
whisperroom is a global whisper not room only < Wrong. Gives Whisper for everyone in the room.
builds club expires shows when your around 1hour (might be swf related) < change default time in users table
pets listen to commands but they do not actually sit when you tell them to < already said that the command id isn't the same in habbo client, need to check how they enumerate the cmds.

Also please rewrite your issue, is hard to understand here.
Paragraphs, etc.

And please check if really is an issue and not a thing that you only don't know.

**Comment by ImNotSatan** [comment]
Whisperroom sends a whisper to everyone, wich is in a room
http://prntscr.com/9vgdhb

I tink your right on the buildersclub, and pets.

**Comment by sant0ro** [comment]
Can you put the error code in Github Markdown?

Is more easy to read.

**Comment by ImNotSatan** [comment]
Ah did not know how to do that thx

**Comment by sant0ro** [comment]
Ambassador Chat only work if you're the rank of Ambassador.
Also the messages only arrives for who is Ambassador. Not for Staff and Ambassadors.

Monster Plants error? Check your catalog. In pixarhotel.com.br works perfectly.

I Will see OneWay gates.

**Comment by sant0ro** [comment]
Room Promotion Works, but you freezes. Need reenter room. After reentering room, the Promotion Enables.

I think this happens because the 'buy" room promotion packet has wrong structure.
Because the room doesn't crashes. You only leave the room in emulator logs.
