### ISSUE TITLE
Some small bugs/issues

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#52]
- **Mannequins**
  In your db the interaction type is: mannequi
  But it should by: mannequin
  Would be a typo, or on purpose
  Annyways it broken, after your name it correctly it disconnects you on click

- STATE: **fixed**

- **Whisperroom command**
  Sends a whisper to every room in the hotel, not the room your in so it does the same as whisperhotel

  - **New code: (this is the wired message ..xD)**
  <pre>
  using Yupi.Game.Commands.Interfaces;
using Yupi.Game.GameClients.Interfaces;
using Yupi.Game.Rooms;
using Yupi.Game.Rooms.User;
namespace Yupi.Game.Commands.Controllers
{
    internal sealed class WhisperRoom : Command
    {
        public WhisperRoom()
        {
            MinRank = 6;
            Description = "Whisper to everyone in the room";
            Usage = ":whisperroom [MESSAGE]";
            MinParams = -1;
        }

        public override bool Execute(GameClient session, string[] pms)
        {
            string message = string.Join(" ", pms);
            Room room = Yupi.GetGame().GetRoomManager().GetRoom(session.GetHabbo().CurrentRoomId);
            room.GetRoomUserManager().GetRoomUserByHabbo(session.GetHabbo().Id);
            foreach (RoomUser user in room.GetRoomUserManager().GetRoomUsers())
            {
                user.GetClient().SendWhisper(message, true);
            }
            return true;
        }
    }
}
</pre>

- **Shutdown still bugs at saving inventairy sometimes**

- **As fas as i know everytime, i reboot my emu (all works fine)**
  The first user who connects after reboot sometimes gets an exception:
  <pre>
Exception logged 01/29/2016 02:43:17 in Yupi.Data.ServerCpuLowPriorityWorker.Process:
MySql.Data.MySqlClient.MySqlException (0x80004005): There is already an open DataReader associated with this Connection which must be closed first.
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Yupi.Data.ServerCpuLowPriorityWorker.Process()
Source:
MySql.Data
Data:
Message:
There is already an open DataReader associated with this Connection which must be closed first.
Stack trace:
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlCommand.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Yupi.Data.ServerCpuLowPriorityWorker.Process()
</pre>

- **Small wired bugs/uncoded parts**
  Screen: http://i.imgur.com/ajtsj3w.png

- **Onewaygate**
  verry unstable/buggy

**Comment by BryanSuero** [comment]
I think the mannequins is mal formed packet

Here is a new packet from Habbo: //[0][0][0]V[3]“ÿÿÿÿ[0]1hr-893-42.hd-190-14.ch-215-71.lg-275-64.sh-295-64[0][1]m[0]Habbo es lo mejor :)[0][0][6]C

And the emulator first put the gender, after figure, and after outfit_name, i going to try fix that.

**Comment by BryanSuero** [comment]
I fixed that in Yupi.Game.Catalogs.CatalogManager (CatalogManager.cs) in Interaction.Mannequin i change the look.

Replace: case Interaction.Mannequin:
                        extraData = string.Concat("m", Convert.ToChar(5), "ch-215-92.lg-3202-1322-73", Convert.ToChar(5), "Mannequin");
                        break;

To: case Interaction.Mannequin:
                        extraData = string.Concat("m", Convert.ToChar(5), "lg-270-82.ch-210-66", Convert.ToChar(5), "Mannequin");
                        break;

**Comment by sant0ro** [comment]
Hello @BryanSuero can you Fork my repository and do a Pull Request with this fix?

Thanks!

**Comment by sant0ro** [comment]
Hello @ImNotSatan i know the bug of the DataReader.
The problem that happens is sometimes the query execution didn't finished and the Emulator try to use the Instance for other things.

Because i coded reusable Connections.
I need to code to the Emulator wait the query finishes.

Sometimes aleatory he reuses, so i need to code to check if is in use, before try to reuse. Going to code this today.

**Comment by sant0ro** [comment]
Also @ImNotSatan these wireds works, you only need put correct interaction type like is said in InteractionTypes.cs

With me the wireds works.

**Comment by ImNotSatan** [comment]
@sant0ro what i ment about the wireds was, like this
![Gif](http://secretup.com/uploads/1ezgif.com-video-to-gif.gif?img=18)

**Comment by sant0ro** [comment]
Wow! That's really weird.

@BryanSuero can give me a help?

**Comment by sant0ro** [comment]
Referencing in Major Thread, closing.
