### ISSUE TITLE
Overflow bugs

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#54]
I assume this problem occurs with:
Wireds, Customrooms

Error logs:
http://pastebin.com/2Q3Kgg18

**Comment by ImNotSatan** [comment]
Also happens with inventory

**Comment by sant0ro** [comment]
Thanks. I will see later.

**Comment by sant0ro** [comment]
I didn't understood the also happens with inventory.

I tested in PixarHotel no-one wired give overflow
Also Custom Rooms doesn't give
Also Inventory now 100%...

**Comment by ImNotSatan** [comment]
These overflows just come on random times :[

**Comment by ImNotSatan** [comment]
EDIT: will try this with the newest source, see if i still get the errors

**Comment by sant0ro** [comment]
...

**Comment by ImNotSatan** [comment]
Probleem seems solved did not see anny new Overflow errors

**Comment by bblackv** [comment]
did u fixed anything?

**Comment by ImNotSatan** [comment]
@bblackv

No overflowd just fixed it in the newest source release
