### ISSUE TITLE
Shutdown issue /Detailed

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#55]
Shutdown bug:

This took me quite a while to figure out lol but,

In my case it stucked here:
<pre>current2.GetHabbo().GetInventoryComponent().RunDbUpdate()</pre>

At this code from RunDbUpdate

<pre>
if (_mRemovedItems.Count > 0)
            {
                lock(_mRemovedItems)
                {
                    using (IQueryAdapter queryReactor = Yupi.GetDatabaseManager().GetQueryReactor())
                        GetClient().GetHabbo().CurrentRoom.GetRoomItemHandler().SaveFurniture(queryReactor);

                    foreach (UserItem userItem2 in _mRemovedItems.Values)
                    {
                        if (SongDisks.Contains(userItem2.Id))
                            SongDisks.Remove(userItem2.Id);
                    }
                }
                
                _mRemovedItems.Clear();
}
</pre>

The line:                         <pre>GetClient().GetHabbo().CurrentRoom.GetRoomItemHandler().SaveFurniture(queryReactor);</pre>

Then at the
<pre>
public void SaveFurniture(IQueryAdapter dbClient, GameClient session = null)
</pre>

It does NOTHING at all O_o?

Just stucks,

**When does this happen?**
I feel like this happens when you pickup a pet, and then like buy items from cata rsomthing

Shutdown stuck happens 100% for me when:
I pickup a pet from a room,
Pickup items from a room
Buy items from cata
Put items in a room

if i do all 3 of those, emu stucks at the SaveFurniture();

SaveFurniture() Just seems broken

In:
<pre>
public void SaveFurniture(IQueryAdapter dbClient, GameClient session = null)
</pre>

GameClient session = null
Might be the problem

Thats just verry weird with the

<pre>
if (session != null)
session.GetHabbo().GetInventoryComponent().RunDbUpdate();
</pre>

Basicly:

If the shutdown skils the 
<pre>GetClient().GetHabbo().CurrentRoom.GetRoomItemHandler().SaveFurniture(queryReactor);
</pre>

It shuts down normally,
If it does do the
<pre>GetClient().GetHabbo().CurrentRoom.GetRoomItemHandler().SaveFurniture(queryReactor);
</pre>

It stucks 100%
I have
<pre>
public void SaveFurniture(IQueryAdapter dbClient, GameClient session = null)
{
Console.WriteLine("Stuff");
</pre>

And it does not even show that, altough it does perform the SaveFurniture
(lots of WriteLines to check l0l, im nub i know)

**BTW**, users without rights can pickup your pets thats weird :O

**Comment by sant0ro** [comment]
See the last commit.
I also thinking there.
Also doesn't make sense emulator save again all data, since at user disconnection and room unloading their respective data are saved.

**Comment by ImNotSatan** [comment]
Well (for me)

I had alot of checking writelines,

It only saves when it skips 
                        GetClient().GetHabbo().CurrentRoom.GetRoomItemHandler().SaveFurniture(queryReactor);

Because there is nothing to update rsomthing?

The SaveFurniture has never succesfully executed

Really weird why it doesnt work tbh

**Comment by sant0ro** [comment]
I'm checking the code. Patiente plz.

**Comment by ImNotSatan** [comment]
Check this:
https://www.youtube.com/watch?v=G1Jb2wwpjk0&feature=youtu.be

This will make u WTF

Mostly at the end, thats why it doesnt save

(Dont mind the Client.Values error in the emu l0l, wrong writeline)

**Comment by sant0ro** [comment]
Fixed.
