### ISSUE TITLE
Blackwordfilter bug

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#56]
If you type a word witch is filtered in a room it works fine

But if you type it in private chat to someone you will see this

![img](http://i.imgur.com/NrroXVH.png)

And when you close that this comes

![img](http://i.imgur.com/wyuiibU.png)

Also for some weird reason you cannot have a dot (.) in ur blackwordfilter

**Comment by sant0ro** [comment]
Yea but is exactly how habbo works.

**Comment by BryanSuero** [comment]
Sant0r0, sorry for write here lol, i fix the home room

**Comment by sant0ro** [comment]
Only change the portuguese word to english.
