### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by Zortex04** [sant0ro/Yupi#58]
hey when importing the sql file it says this

SQL query:

DROP EVENT `daily_pet_respect_points`
MySQL said: Documentation

#1539 - Unknown event 'daily_pet_respect_points'
i dont know if daily respect points are important or not

**Comment by sant0ro** [comment]
Are. 
Only remove the DROP EVENT LINE.
Is because you doesn't have these EVENTS.

**Comment by Zortex04** [comment]
??? i am not trying to drop them but it says that when importing the sql file but now on a hosted mysql it says 

SQL query:

DELIMITER $$--
-- Eventos
--
DROP EVENT `daily_pet_respect_points` $$

MySQL said: Documentation

#1044 - Access denied for user 'b18_16882580'@'192.168.0.%' to database 'b18_16882580_habbo'

**Comment by sant0ro** [comment]
Also need change the @localhost and these things, to your user.
