### ISSUE TITLE
users_online removed?

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#60]
Why did you remove this in: **ServerCPULowPriorityWorker**...

<pre>
                    using (IQueryAdapter queryReactor = Yupi.GetDatabaseManager().GetQueryReactor())
                    {
                        if (clientCount > _userPeak || realOnlineClientCount > _userPeak)
                            _userPeak = realOnlineClientCount;

                        queryReactor.RunFastQuery(string.Concat("UPDATE server_status SET stamp = '",
                            Yupi.GetUnixTimeStamp(), "', users_online = ", realOnlineClientCount, ", rooms_loaded = ",
                            loadedRoomsCount, ", server_ver = 'Yupi Emulator', userpeak = ", _userPeak));
                    }
</pre>

This shows the online coun in the cms?

(you removed the real usersonline so should be like this now)>

<pre>
                    using (IQueryAdapter queryReactor = Yupi.GetDatabaseManager().GetQueryReactor())
                    {
                        if (clientCount > _userPeak || clientCount > _userPeak)
                            _userPeak = clientCount;

                        queryReactor.RunFastQuery(string.Concat("UPDATE server_status SET stamp = '",
                            Yupi.GetUnixTimeStamp(), "', users_online = ", clientCount, ", rooms_loaded = ",
                            loadedRoomsCount, ", server_ver = 'Yupi Emulator', userpeak = ", _userPeak));
                    }
</pre>

**Comment by BryanSuero** [comment]
clientCount and realOnlineClientCount was the same.

**Comment by ImNotSatan** [comment]
Yeah but its complete removed and the server_status does not update now annymore

**Comment by BryanSuero** [comment]
That is because the if in this case is so stupid I going to check.

**Comment by sant0ro** [comment]
Because is really useless do a query do Database saying who many users is only if you can count in your cms doing the following query:

<pre>
SELECT COUNT(online) FROM users WHERE online = '1';
</pre>

Is really pretty better.
Since isn't good every 10 seconds do a Query to Update the Count. 
The ServerCPULowPriorityWorker is attached to Main Game Loop. If this Class crashes maybe main Game Loop can crash.
