### ISSUE TITLE
Floorthickness does not save

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#61]
if you change the floorthickness to smalles and type :reload its back to big

Also you prolly made a typo here:
**RoomManager.cs**
<pre>
queryReactor.AddParameter("wallthick", Yupi.BoolToEnum(room.RoomData.AllowPets));
</pre>
Says it all... xD

**Comment by sant0ro** [comment]
Wow kkk

**Comment by sant0ro** [comment]
Thanks i will fix.
