### ISSUE TITLE
Relationships don't update

### ISSUE THREAD

**Issue by JAysz0n** [sant0ro/Yupi#62]
Relationships doesn't work because the Id's are not auto incremented;

DROP TABLE IF EXISTS `users_relationships`;
CREATE TABLE `users_relationships` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `target` int(11) NOT NULL,
  `type` enum('1','2','3') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

**Comment by ImNotSatan** [comment]
Relationships work fine for me?

**Comment by sant0ro** [comment]
This bug doesn't exists.

**Comment by JAysz0n** [comment]
http://prntscr.com/a0yrf9
This is what happens to me when I use your table structure, so no relationship will be shown.

**Comment by sant0ro** [comment]
ID Is an unused field that will be removed.
