### ISSUE TITLE
Weird loggin

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#64]
For some reason at logging in:

YupiLogManager.LogException(ex, "Registered Login Exception.", "Yupi.Users");

It does not display/write an error in the logs folder

(After a while i addded the error manual and saw it was that online_seconds in user_stats wasnt set to be default: 0)

But somthing seems wrong with some loggings.

**Also**
In the clothes editor, if you change gender, the look does not change in the editing screen

(Does work when you save)

**Comment by sant0ro** [comment]
You're dummie!
See commit logs!
Now Logs goes on Database in server_system_logs.

Closed.

**Comment by ImNotSatan** [comment]
Oow lool hahaha i missed that

**Comment by sant0ro** [comment]
;)
Remember see commits before say that exists bugs haha
