### ISSUE TITLE
Yupi Statement!

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/Yupi#66]
As you can see our new branch "nio" is under development. When the Beta code goes to Work, will be switched to "master" branch.

What means the new "nio" branch?
Following the Main Milestone the Major things for being developed now are:
1. Connection and Socket System/Service/Management Rewrite
2. Also will be Rewrited GameClientManager and GameClient
3. The Encryption System will be totally removed from Yupi. Remaining only the RC4 Library. The reason of that is since doesn't exists any Client Side RC4 Library for any emulator (The Server Side RC4 is for Client => Server, and Client Side RC4 for Server => Client) that's not needed. Also i need to say that the New "Automatic" Cracking System, by default removes RC4 Algorithm from Habbo.swf. Since that isn't anymore needed RSA Handshake. 
Removing entirely the RC4 and Encryption System isn't a Security Issue. Since this Algorithm created by Sulake was intended to the people Can't get the "true" content of a Packet.
The fact is every Packet Logger already decipher the RC4 and avoid the RSA Handshake in Proxy Connection.
Since that the best methodologie of security to be used in Yupi is Server-Side Security.
Emulators Like Azure have security fails, like you can give Diamonds or Change your Credit Amount. (In Packet Logger) that happens because these emulators doesn't check if the Data is Valid. Since they receive from client a new Diamond/Credits value they Accept it without any questions.
In Yupi the GameClient system and Security System will completely rewrote. but doesn't expect NOW high security since the Emulator is on Alpha Stage Development.

The Security Concepts in Yupi Will be:
1. Removing Breackable Client System, removing entirely bad delegate system, and bad Client System. GameClient and GameClientManager will be completely rewrited.
2. The new Connection Manager will be (as intended) Helios-io. A Ready NIO Net Framework, ready for Reactive Connections. Is a really good and awesome Framework.
3. Every Query as Possible (receiving client data) will be passed in Prepared Statements.
4. Purchasing Items with Fake Credits/Exchange Amount will be avoided, since the Value of the Purchase (as for packs or multiple items) will be directly confirmed by Database, and not the value sended by client.
5. User Status Update Packet, will not be allowed to update Users Data, since your credits amount only increase/decrease when Staff does internal commands (that are good checked) and with items purchases/sells. Also the Avatar Look will be passed by AntiMutant System. Data like Gender will also be Checked.
6. Azure Emulator has RoomItem security issue, since you can Multiplier or Stack Furniture Amount our Put Furniture via Packet Logger kwnowing their Item Ids. Also a security issue that  Azure Adds items to your database if they're in the Room but not in Database! The Item System is being rewrite were will be:
A. Interacion System will be Abstract and Dynamic where every Interacion has their Composers and Own "Model" with Basic States (Place, Remove, DoubleClick, SingleClick, Update, Rotate, Etc)
B. Items that aren't in Database but are in Room will be Avoided and Skipped.
C. Purchasing Item will be dynamic where every Interaction has their own Purchase "Model".
D. Special Switches or If/elses that are checked by Item Name will be avoided. Adding Interactions to these Items. Example: HabboClub Subscription is checked by Item Name (Literally!) Special Items that doesn't exists in FurniData or are special like Subscriptions, Pets, Bots, Etc will have their own Table where we have (Pets, Bots, Subscriptions, SpecialItems).

7. Pet Command System rewrite will be continued.

8. The Server Security System for (Bots, Mutants, Publiciters (That Spams other Hotels) and "Hackers" That tries using Packet Logger) will be highly rewrited.
Where a "Score" system will be Coded. The Score System will have some special actions and verifications:
1. If the IP does a lot of Connection Pooling or New Connections (Open/Close) will be Machine Banned (DoS Protection) (but every connection increase the "Bad Point System"
2. Hotel Filtering System will be improved with Inference Service, where if a BlackWord hotel (like Hatop) a similar word like "Ha" (other message) "Top" will be given as Hatop (That means that not only the system will check the existence of the BlackWord in a Single Message, but multiple messages, increasing bad score).
3. Weird Looks will increase score.
4. Users with Weird Usernames with Blackwords will have bad score
5. Users trying to use Input System (navigator search, chat, messenger, create room, (inputs)) with weird symbols, and injection symbol combinations will increased bad points.
6. Multiple Fake accounts per Ip will increase bad score.
7. Packet Logger increase score.

The score depending of amount can ban permamently in Database or Temporary ban (if emulator restart temporary ban is removed).

8. Yupi will have a new complete Log Service, Since log4Net is Done now, Every Staff Action will be logged, Emulator Debug Data, Thread Logs, Crashes, Unexpected Connections, Everything that is relevant.

9. Intendeed to a new Caching System. The UserCached System will be rewrite also Item Cache System will be. Will also be coded new Cache System for Rooms and Users Constraints Data (Friends, Ignores). All this data will be in the new Yupi Cache Factory, with SubModules (like RoomCacheModule, etc, that are totally dynamic with dynamic configuration like as GC Interval, Buffer Amount, Stored Data, Sensibility for Dispose Data, Data Priority, etc.)

10. More.
Remembering this is the Major Issue List. And all these things will be coded and "maked" before doing any other in-game or other issue Related.

So if you are expectating new in-game features or in-game bug fixes. Don't expect that!
Now the yupi will start the complete refactorement. High Database Changes can Happen. And also between commits instability and bugs can be HIGH.
Soo the Master branch will not anymore being updated. And the new development will continue in "nio" branch.

After this Issue be done. Master branch will be updated. And normal development continues.

Sincerely.

**Comment by ovflowd** [comment]
NIO Rewrite as Far i can see is Done.
