### ISSUE TITLE
'extra_data' in 'items_rooms'

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#69]
**(this is with the new commits)**
I found quite some people sturggling with this issue,

In your old database (before the release of the new cata etc)

'**extra_data**' was a **varchar(7000)**

But in the newest database (new cata etc)

You changed the **varchar(7000)** to a **text**

Because of this people cant buy furni and for some weird reason, when i buy furni with the **extra_data** as a **text**

All items_rooms id's will become '**0**'

For some weird reason.

But if i change it back to **varchar(7000)** it works totally fine

**Comment by ovflowd** [comment]
Ok i will search about it.
