### ISSUE TITLE
Yupi Emulator: Documentation Sprint

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/Yupi#7]
# Documentation
**Here will be tracked and reported documentation progress and related things**

## Assigned
- @Rockster34 
- @CineXMike

**Comment by sant0ro** [comment]
@Rockster34 @caio1478 @CineXMike Will do the Documentation

**Comment by sant0ro** [comment]
@Rockster34 Will you do this?

**Comment by Rockster34** [comment]
Yes i'll do that

**Comment by sant0ro** [comment]
@Rockster34 Any progress?

**Comment by ovflowd** [comment]
Documentation is Paused. Since we're rewriting Core.
