### ISSUE TITLE
Multilog bug

### ISSUE THREAD

**Issue by ImNotSatan** [sant0ro/Yupi#70]
[youtube](https://www.youtube.com/watch?v=Iot-hBbiGzg&feature=youtu.be)

It results into 1 connection only, wich is verry weird

If 1 users connects on th same, ip you basicly disconnect (but your sessions stays active), and your able to control the other user (if the user is in the same room)

**Comment by ovflowd** [comment]
I can't watch the video.
It's privated.

**Comment by ovflowd** [comment]
How you can control it if disconnects?
If you enter in a new navigator the old user is disconnected. with reason entered other client.
but if the conn id is the same, the new connection is destroyed and the old remains. Since some times people open navigator accidentally.

**Comment by ImNotSatan** [comment]
I unprivated it, and idk its really really weird

But this is with diffrent users accounts (also diffrents sso)

i feel like sessions are ip-linked for some reason
[youtube](https://www.youtube.com/watch?v=Iot-hBbiGzg&feature=youtu.be)

**Comment by ovflowd** [comment]
Wow that's really weird! Are different users yeah?

**Comment by ImNotSatan** [comment]
Yeah

**Comment by ovflowd** [comment]
Fixed in Next Commit. Wait the Commit.
