### ISSUE TITLE
Pick up pets bug

### ISSUE THREAD

**Issue by RayRenirie** [sant0ro/Yupi#71]
When I pick up a pet (tested with that chicken pet) I can't walk or place any furniture back on that place.

**Comment by ovflowd** [comment]
Really? I will check that.
Are u using last Yupi?

**Comment by RayRenirie** [comment]
I'm using that master, tested it on the latest and that roger 1.0.0 version.

**Comment by ovflowd** [comment]
Pleae try downloading latest ZIP from "nio" branch. And Compile it.

**Comment by RayRenirie** [comment]
I can't compile the nio branch, it gives me a lots of errors.

**Comment by ovflowd** [comment]
Which errors?

**Comment by RayRenirie** [comment]
Severity    Code    Description Project File    Line
Warning CS7035  The specified version string does not conform to the recommended format - major.minor.build.revision    Yupi    C:\Users\Ray\Desktop\Yupi-nio\Yupi-nio\Yupi\Properties\AssemblyInfo.cs  20
Error       "git.exe" exited with code 128. Yupi    C:\Users\Ray\Desktop\Yupi-nio\Yupi-nio\Yupi\Yupi.csproj 756

Oh, it is 1 error and 1 warning now.

**Comment by ovflowd** [comment]
The Warning is nothing to matter.
The git,exe is because you Didn't Cloned the REPO but Downloaded the ZIP..
You can clone using Github Desktop. (You Need Git..)

Because Yupi has now integrated Version Scanning..

**Comment by RayRenirie** [comment]
I will try! Thanks.
