### ISSUE TITLE
Problem with same IP and Proxy ( Same IP for all users )

### ISSUE THREAD

**Issue by Killua99x** [sant0ro/Yupi#72]
When you use a proxy or the same IP (if you are using a proxy is like having all the same IP) for two clients the emulator does disconnect one of the two users online, so you can use either a proxy, you can solve this error in future versions? Thanks in advance

**Comment by ImNotSatan** [comment]
Ow yeah l0l

**Comment by ovflowd** [comment]
Sorry but i didn't understood. Can explain better?
Are using last version of Yupi?

**Comment by ImNotSatan** [comment]
He ment this,

When you use a TCP proxy 

All users basicly have the same
Ip (the proxys ip)

But the users are limited to 1 per ip

so basicly u can have MAX 1 online with a tcp proxy

**Comment by Killua99x** [comment]
@ImNotSatan Yes, Thanks and sorry, i'm italian and i study english

**Comment by Killua99x** [comment]
"But the users are limited to 1 per ip" how can i edit it for support infinity user with 1 ip?

**Comment by Killua99x** [comment]
I dont understand this problem http://prntscr.com/aash8k a few minutes ago I hadn't.

**Comment by Killua99x** [comment]
With new Version of Yupi i have this error http://prntscr.com/aasngi @sant0ro

**Comment by ovflowd** [comment]
New Version is fixed. (I fixed now)

**Comment by Killua99x** [comment]
@sant0ro you fixed limited connection for IP?
