### ISSUE TITLE
Error GitVersion

### ISSUE THREAD

**Issue by Killua99x** [sant0ro/Yupi#73]
Hi, i have the latest version for yupi and i have this error http://prntscr.com/ab5ycm ( i download now the latest version ) @sant0ro 

http://prntscr.com/ab5zc7

**Comment by Killua99x** [comment]
http://prntscr.com/ab7kzi on Windows 10 i have this error

**Comment by ovflowd** [comment]
Hi, clone the Repository using Github Desktop ;) (Don't use Download ZIP)

After Clone, open the Visual Studio Solution File. Click Build, automatically Visual Studio will try recover NuGET Packages.

**Comment by Killua99x** [comment]
@sant0ro sorry, i dont understand, i have GitHub Desktop on VPS and on my sistem

http://prntscr.com/ab8tg6

---

http://prntscr.com/abh4g3

http://prntscr.com/abh1so

http://prntscr.com/abh1w9

http://prntscr.com/abh23n

**Comment by ovflowd** [comment]
You need open the Visual Studio Repoistory directly from the folder where you CLONED the repo.

Almost like C:\Users\YouUser\Documents\Github\Yupi...

**Comment by Killua99x** [comment]
yes i now, I did just that and i have this error

http://prntscr.com/abj5ze

http://prntscr.com/abj64u

i recloned Yupi on Github folder 

http://prntscr.com/abj6es

**Comment by ovflowd** [comment]
Observation: Try Build as x64
And Restore FIRST nuget packages.

Also try deleting .build folder first.

**Comment by ovflowd** [comment]
Remember that if the NuGET MSBuild Extensions Tools aren't added, the "GitVersion" tool will not be work.

**Comment by Killua99x** [comment]
Sorry how i can install NuGET MSBuild Extensions Tools ?

**Comment by Killua99x** [comment]
I try to  delete .build folder and Yupi project can't load

http://prntscr.com/ablx2g

i download again the clone with github application 

http://prntscr.com/abm4mq

**Comment by sant0ro** [comment]
O Yupi já faz isso.. Quando você tenta fazer  Build..

Tente fazer o seguinte:
1. Visual Studio > Tools > NuGET > NuGET Packages Tool (não é o console)
Veja se tá tudo lá.

Pelo que vi no print já tá.

**Comment by ovflowd** [comment]
That doesn't make any sense.

**Comment by ovflowd** [comment]
I can't reproduce this bug. The solution is have Cloned Repo, but still doesn't work with u.

**Comment by Killua99x** [comment]
Boh i have all correctly and dont work 

http://prntscr.com/abmgab

http://prntscr.com/abmguq

**Comment by ovflowd** [comment]
I really can't know what is happening here.

**Comment by ovflowd** [comment]
Download: https://git-scm.com/downloads
Only Install the Application for Windows, after that relaunch Visual Studio and try Build.

**Comment by Killua99x** [comment]
Thanks now i try
on my Windows VPS http://prntscr.com/abndj0 

I install GIT and i have same error

**Comment by Killua99x** [comment]
Sorry, ho i can bypass this problem?

**Comment by ovflowd** [comment]
After install GIT, you need restart PC.

**Comment by ovflowd** [comment]
(VPS in this case)

**Comment by Killua99x** [comment]
Ah Thanks! i try!

---

Nothing.. same error

**Comment by ovflowd** [comment]
Same error?

**Comment by ovflowd** [comment]
That really doesn't make any sense. Please try using a normal Windows PC, With Windows 7 or Windows 10. Remember using Visual Studio 2015 or later, Community Version or Higher,

Sorry but i can't help. I will attach new Executables in some few days. (New release)

**Comment by Killua99x** [comment]
yes, i can't resolve it .. I don't understand why it does that is it okay

I try on my laptop with WIndows 10 with visual studio 2015 Enterprise same error

If you put executables could you please fix the problem that every user must have a different Ip?
(insert unlimited IP for users )

with proxy can i have 1 user online

So me and other people can use proxy

Thank you for your patience

**Comment by Killua99x** [comment]
@sant0ro Sometimes the client goes black, some of the rooms become bugs and after entering those rooms the client goes black

many times after you close the emulator the rooms don't have furnis

**Comment by ovflowd** [comment]
'If you put executables could you please fix the problem that every user must have a different Ip?
(insert unlimited IP for users )' i didn't understood that.

Also this last comment, is a old version of yupi?

**Comment by Killua99x** [comment]
Yes @sant0ro now i use the old version of yupi 

with proxy i can have 1 user on client because with 2 same IP users can't enter on client

I can't use latest version of yupi for git.exe error con Virtual Studio

**Comment by ovflowd** [comment]
Old version i don't give support. Wait for new executables ;)

**Comment by Killua99x** [comment]
@sant0ro Thanks for all!

**Comment by BryanSuero** [comment]
Here is how I fixed this problem. 

**Search for Yupi.csproj**
![Solution for Git problem](https://i.gyazo.com/268c4c3bce0a18973ec13b9b6efbeaad.gif)
**Find and open Yupi.csproj with any text editor**
![Solution for Git problem](https://i.gyazo.com/437fac976a3cf6133d191eb5d3c0585b.gif)
**Search for GitVersion (at the end of the file) and erase like this GIF. save and re-open the project in visual studio**
![Solution for Git problem](https://i.gyazo.com/3067366aa663ab9bb2153220e576f5b2.gif)

Thanks :v:

**Comment by Killua99x** [comment]
Thanks!! @BryanSuero Now i have problem with furnidata xD ( i resolve furni data )
Now i have this 
http://www.sunake.org/upload/images/2016/03/06/Screenshotfrom2016-03-0621-07-05.png  @sant0ro

**Comment by BryanSuero** [comment]
Put a correct URL in the setting, and delete the cache of the furnidata.

**Comment by Killua99x** [comment]
Yes i put the correct url can you see the screen? i dont understand the error

**Comment by BryanSuero** [comment]
Which screen?

**Comment by Killua99x** [comment]
this http://www.sunake.org/upload/images/2016/03/06/Screenshotfrom2016-03-0621-07-05.png

**Comment by BryanSuero** [comment]
Check your config

**Comment by Killua99x** [comment]
is correct

```
## Yupi Server Other Extra Settings

## RC4 Client Side (ARC4) Beta
rc4.client.side.enabled=false

## Currency Loop Settings
currency.loop.enabled=true
currency.loop.time.in.minutes=15

## Amount of Credits to Give
credits.to.give=3000

## Amount of Pixels to Give
pixels.to.give=100

# Diamonds Loop Settings
diamonds.loop.enabled=true
diamonds.vip.only=false

## Amount of Diamonds to Give
diamonds.to.give=1

## User able to Change Name Settings
change.name.staff=false
change.name.vip=false
change.name.everyone=false

## Habbo Camera Settings
stories.api.enabled=true
stories.api.url=http://www.sunakehotel.com/resources/server-camera/server-camera.php?run
stories.api.host=http://www.sunakehotel.com/resources/server-camera/
stories.api.thumbnail.url=http://www.sunakehotel.com/resources/server-camera/server-camera.php?room

## Furniture (ex: furnidata_xml.xml) XML File URL
furnidata.url=http://www.sunakehotel.com/resources/swf/gamedata/furnidata_xml/1

```

**Comment by Killua99x** [comment]
```
## Yupi Server Main Settings

## MySQL Configuration
db.hostname=( i remove it)
db.port=3306
db.username=root
db.password=( i remove it)
odb.name=snk

## MySQL pooling setup (controls amount of connections)
db.pool.minsize=1
db.pool.maxsize=5

## Game TCP/IP Configuration
game.tcp.bindip=( i remove it)
game.tcp.conlimit=11000
game.tcp.enablenagles=true

## Connection System Pooling 1 = Single Thread, 0 = Infinite
game.tcp.boss.maxthreadsize=5
game.tcp.work.maxthreadsize=0

## Game TCP/IP Port Configuration
## Normal Port (The Emulator Port)
game.tcp.port=port ( i remove it)

## Proxy Port (Need be the Same as the Emulator Port)
## Only change If you're using Proxy. If is put your Proxy Port Here
game.tcp.port.proxy=port ( i remove it)

## Game Thread Configuration
game.multithread.enabled=false

## Tcp Flood AntiDDoS  Comment: For proxy antiddos=false
game.tcp.denialservice=false
game.tcp.max.connperip=100

## Bots Settings
game.roomswithbotscolor=0
game.botdefaultcolor=31
game.botbadge=BOT

## Client Release Version
client.build=PRODUCTION-201510201205-42435347

## Client configuration
client.ping.enabled=1
client.ping.interval=20000

## Client Friend Configuration
client.maxfriend.requests=300

## Client Thread Configuration
client.multithread.enabled=false

## Debug Packet Data
debug.packet=false

## Language System
server.lang=english

## Console Clear Timer
console.clear.enabled=false
console.clear.time=20000

```

**Comment by Killua99x** [comment]
http://www.sunake.org/upload/images/2016/03/06/Screenshotfrom2016-03-0623-31-04.png

**Comment by BryanSuero** [comment]
Check your database now, do you have skype or something like that? Or we can talk here https://gitter.im/sant0ro/Yupi

**Comment by Killua99x** [comment]
yes my mail for skype is pedrowizand@outlook.com

i dont understand the table problem i dont have a log file

**Comment by BryanSuero** [comment]
I addeed you

**Comment by ovflowd** [comment]
what is "odb.name=snk"

**Comment by ovflowd** [comment]
why you putted ODB if is DB?

**Comment by Killua99x** [comment]
Ops, sorry xD i wrong 

---

Sorry now it is correct and i have this problem

http://prntscr.com/acam1l

Unknown column 'id' in 'order clause' 

I dont understand that

**Comment by BryanSuero** [comment]
Kira, that problem is because you had a wrong database, please use the new SQL file.

**Comment by Killua99x** [comment]
@sant0ro sorry xD i resolved

Yupi has many bugs but I'm sure you will solve

It is the best emulator for me

I use it on www.sunakehotel.com but is in maintenance because it still has many bugs in the rooms, furni etc..

**Comment by ovflowd** [comment]
Many bugs? Please tell me which bugs.

Yupi doesn't has many bugs....

'-'

You need using Yupi BuiltIn Catalogue.

**Comment by Killua99x** [comment]
each does not enter the rooms by the users, each both crashes, the client goes black and does crash the user, sometimes users put furni into the room and crash

**Comment by Killua99x** [comment]
i use yupi on www.sunakehotel.com and have so many bug, users report them to me many times and many time crasho myself when I walk into a room that is reported as the room that does crash

**Comment by ovflowd** [comment]
With my test hotel that doesn't happens.

**Comment by Killua99x** [comment]
Boh... i dont know, on my hotel i have that bug.. and other xD

**Comment by Killua99x** [comment]
And i have problem with proxy, without proxy i canhave a unlimited users with proxy i can have 1 users because all users have the same IP

(TCP PROXY)

**Comment by ovflowd** [comment]
Closed.

**Comment by ovflowd** [comment]
Please @KilluaKira create new issue describing this bug.

**Comment by Killua99x** [comment]
Yes Thanks, one moment
