### ISSUE TITLE
Azure to Yupi 

### ISSUE THREAD

**Issue by arjanterheegde** [sant0ro/Yupi#75]
X

**Comment by ovflowd** [comment]
As i said before. You simply cannot use Azure Emulator catalogue in Yupi.
You cannot simply add the columns in database.

Yupi is very attached to the types of variables. Also a lot of interaction types, furnitures, etc. changed. A lot of structure.

You need use Yupi built-in catalogue.

Conversion of other catalogues. Aren't supported.
