### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by RayRenirie** [sant0ro/Yupi#76]
When I try to start the emulator it gives me this error:

http://puu.sh/nHI8e/3947791a21.jpg

**Comment by ovflowd** [comment]
Need use the Packets Folder that are included in Latest Yupi Version.

**Comment by RayRenirie** [comment]
Now I get this error:

http://puu.sh/nIIDo/9f51c99dfd.jpg

**Comment by ovflowd** [comment]
Please use latest Yupi Database. And you will don't receive this error.

**Comment by RayRenirie** [comment]
With new db I get this: http://puu.sh/nKZBU/591d7b5639.png
