### ISSUE TITLE
Yupi release 1.1 can not connect...

### ISSUE THREAD

**Issue by iTzl3lack** [sant0ro/Yupi#79]
Hello,

I get an error if i would connect to my client...
in the server_system_logs is the error message:

> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'user_id' in 'where clause'
>    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
>    at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
>    at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
>    at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
>    at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
>    at Yupi.Emulator.Game.Users.UserPreferences..ctor(UInt32 userId)
>    at Yupi.Emulator.Game.Users.Habbo.Init(GameClient client, UserData data)
>    at Yupi.Emulator.Game.GameClients.Interfaces.GameClient.TryLogin(String authTicket, String& banReasonOut)

I hop you can help me

**Comment by TheDoct0r11** [comment]
Looks like an error produced by an incorrect database. 

Please keep in mind, that Yupi makes no guarantees regarding compatibility with databases of other emulators.

**Comment by ovflowd** [comment]
@iTzl3lack sorry but this doesn't happens with me. Make sure you're with latest database.
Remembering that this error "user_id" as far i can see is referred to users_info table. (but may im wrong)..

Make sure, that everything is right.
