### ISSUE TITLE
Emulator stops working

### ISSUE THREAD

**Issue by RayRenirie** [sant0ro/Yupi#80]
Hello,

After some hours (sometimes minutes) the emulator doesn't accept new connections. You can't connect anymore to the emulator, client hangs at 76%. If you are in the hotel, it will work, but you can't rejoin.

Kind regards,
Ray

**Comment by ovflowd** [comment]
Really that these bug exists? These bug was happening when i started DotNetty implementation. But is already fixed i think..

**Comment by RayRenirie** [comment]
Yes, I have this with your latest 1.1 jesus version, and also on the older ones.

**Comment by ovflowd** [comment]
Okay i will check later.

**Comment by ovflowd** [comment]
@TheDoct0r11 will handle this issue.

**Comment by RayRenirie** [comment]
Okay

**Comment by RayRenirie** [comment]
Has this been fixed yet?

**Comment by ovflowd** [comment]
I don't know, need ask to @TheDoct0r11

**Comment by TheDoct0r11** [comment]
Should be solved as the entire socket system had to be rewritten for Linux.
Please try one of the [current builds](https://ci.appveyor.com/project/sant0ro/yupi/build/artifacts?branch=linux)
