### ISSUE TITLE
DotNetty is a roadblock for linux :(

### ISSUE THREAD

**Issue by TheDoct0r11** [sant0ro/Yupi#83]
Hey there,
just had to find out that DotNetty doesn't seem to care about mono at all.

There is one [issue](https://github.com/Azure/DotNetty/issues/34) at their repository,
but activity is rather low...

I didn't even get to those issues, since I already got stuck with [this](https://bugzilla.xamarin.com/show_bug.cgi?id=27337) resulting in a runtime exception when starting the server. 
(Fix will be in mono 4.4, but I guess it will take some time till that will be released)

DotNetty uses EventSource::WriteEvent and also they don't even try to call the method, this exception is being thrown?!

Sadly this means that either Yupi won't be compatible with Linux or that DotNetty must be exchanged either for another NIO framework or a own (simple) socket implementation...

Greetings
TheDoct0r11

**Comment by Killua99x** [comment]
So nothing Yupi on Linux ..

**Comment by Killua99x** [comment]
If I knew the Java writes Yuppi me everything in java, obviously will release the source

**Comment by TheDoct0r11** [comment]
Probably not without rewriting the networking, which will take some time.
I wrote @sant0ro an E-Mail, since I don't want to make such a major decision on my own.

It looks like [supersocket](http://www.supersocket.net/) would be an alternative,
but I didn't take a exact look at that since it is 01:32 AM here. 

Another, rather extreme solution would be to link to a cross platform C++ library,
but I really think that would pose more problems than it would solve...

I'm sorry, but I don't get your comment about Java.

**Comment by Killua99x** [comment]
@TheDoct0r11 sorry for my english i'm italian, and I mean I just programming, I said if I knew how to program in java rewrite yupi in java for not having problems with linux 

sorry again for my english

**Comment by TheDoct0r11** [comment]
@KilluaKira Yeah, about that...
Ever tried to run Minecraft with OpenJDK on Linux?
It doesn't really work and one has to install Oracles JRE,
which is against the purpose of using an open source operating system...

Also writing an Emulator from scratch requires a LOT of time...

But that really is rather offtopic...

**Comment by Killua99x** [comment]
yes i understand, i use CentOS on my laptop dual boot with Windows 10 pro

**Comment by TheDoct0r11** [comment]
Added Supersocket ( #88 ) to linux branch. 

Startup is now working; Needs testing!

**Comment by ovflowd** [comment]
@TheDoct0r11 i will test last version, okay?

**Comment by TheDoct0r11** [comment]
Of course! 
Would be great if you could benchmark the performance difference between DotNetty (nio branch) and SuperSocket (linux branch) on Windows and upload the results.
