### ISSUE TITLE
Online Counter doesent work

### ISSUE THREAD

**Issue by Killua99x** [sant0ro/Yupi#85]
Hi, @sant0ro, how can i fix the online counter? 

when I connect it does not put on 1 of my online column user and when I'm disconnected obviously does not put 0

**Comment by TheDoct0r11** [comment]
Hi,

caused by missing call to RunQuery in

https://github.com/sant0ro/Yupi/blob/nio/Yupi/Emulator/Game/GameClients/GameClientManager.cs#L326

and 

https://github.com/sant0ro/Yupi/blob/nio/Yupi/Emulator/Game/GameClients/GameClientManager.cs#L340

Will be fixed.

**Comment by Killua99x** [comment]
Ah Thanks! @TheDoct0r11

**Comment by TheDoct0r11** [comment]
Fixed in 42b0ebc
