### ISSUE TITLE
Message Handling

### ISSUE THREAD

**Issue by TheDoct0r11** [sant0ro/Yupi#89]
Hey,
I want to propose a new way of structuring message handlers.

I think it would be a good idea to have the following interfaces:

(subject to change of course)

```
public interface IIncomingMessageHandler {
   string Name { get; }
   void HandleMessage(ISession session, ClientMessage message);
}

public interface IOutgoingMessageHandler {
   string Name { get; }

   void SendMessage(Session session, IParamBag params);
}
```

We could then use reflection upon **start-up** to find the classes implementing these interfaces and map them to the packet names/id's.

This would slow down start-up for a bit (reflection is rather slow) but since there are a lot of I/O operations and database queries anyway that should not matter anyway.

**Comment by ovflowd** [comment]
Yes that was i'm rathering, Reflection would be more slow. A way to index the Handlers will be good.
But also we need create the Composers, i created only few Composers... The way is dynamize the code.
But your idea is approved.

**Comment by TheDoct0r11** [comment]
Composers would have to implement IOutgoingMessageHandler

**Comment by ovflowd** [comment]
Ugg.... Ok.,
