### ISSUE TITLE
Yupi cannot connect to any MySQL server anymore

### ISSUE THREAD

**Issue by ovflowd** [sant0ro/Yupi#90]
I really don't know why. But can't figure it out. Yupi simply doesn't connect to MySQL server. The error isn't nothing related to incorrect or invalid server details. But error when trying to open MySQL driver.

**Comment by TheDoct0r11** [comment]
Can't reproduce on linux....
Would you mind adding the error message and the stacktrace?
And the git commit hash of your version would be good to know :)

**Comment by ovflowd** [comment]
Okay ;)
