### ISSUE TITLE
MSBuild Tasks removal

### ISSUE THREAD

**Issue by ovflowd** [sant0ro/Yupi#91]
1. Need remove entirely MSBuildTasks implementation. Since you need fork the repository to get it working, or being main repository collaborator.
2. We will switch as @TheDoct0r11 suggested that is using Github API Implementation for:
3. Check if current local build is running at latest git version.
4. Get UPDATES.json
5. Other Data..

People can't build Yupi now, using last version because the MSBuildTasks, that need be linked with Git, and injects in AssemblyInfo.

**Comment by TheDoct0r11** [comment]
MSBuild Tasks is removed already.
Will have a look at the API when I get around to it.
