### ISSUE TITLE
Habbo Club Crash

### ISSUE THREAD

**Issue by Killua99x** [sant0ro/Yupi#92]
Crash if i click Habbo Club

http://prntscr.com/anb28m

i have this error with Branch Nio and Linux Branch

@TheDoct0r11 @sant0ro

**Comment by ovflowd** [comment]
Hi maybe is wrong packet. I will analyse.

**Comment by Killua99x** [comment]
If you need  screenshots tell me

**Comment by ovflowd** [comment]
Okay, i can't do this now, while i'm sick and studying. But i have 99% certain that or is wrong packet when i updated the release, or wrong structure.

**Comment by Killua99x** [comment]
I'm sorry, as soon as you're fine, good healing Claudio

**Comment by ovflowd** [comment]
Thanks

**Comment by ghost** [comment]
Work fine for me.  
I dont have this bug.

**Comment by ovflowd** [comment]
Nice, Anthologique don't have this. Closing issue.

**Comment by ovflowd** [comment]
Also @Anthologique i need your skype.

**Comment by Killua99x** [comment]
@sant0ro  I put a video in youtube for it...

**Comment by ovflowd** [comment]
But @Anthologique said is working.. Maybe the error is only with u?

**Comment by Anthologique** [comment]
@sant0ro Give me your Skype, i add you.

**Comment by ghost** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15547050/7bf573d2-22a2-11e6-9322-7ac28f350fe6.png)

**Comment by sant0ro** [comment]
@Anthologique my skype is 'live:sant0ro'

**Comment by Anthologique** [comment]
I have you on my Skype, you have lock me...
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15549250/0af7ab50-22ac-11e6-9243-0752419dd413.png)

**Comment by sant0ro** [comment]
@Anthologique tell me your skype name please.

**Comment by Anthologique** [comment]
Anthologique

**Comment by sant0ro** [comment]
Tried to add. You aren't on contact list.

**Comment by Anthologique** [comment]
you have lock me...

**Comment by ovflowd** [comment]
Here you aren't locked and aren't added.

I will delete these off-topic messages from the issue. ;)

**Comment by Killua99x** [comment]
@sant0ro  now i try a new version of yupi and i dont have this issue °-° en.sunakehotel.com

**Comment by ovflowd** [comment]
Oh yeah

**Comment by Killua99x** [comment]
on linux it doesent work with mono

**Comment by ovflowd** [comment]
@KilluaKira can't register.

**Comment by Killua99x** [comment]
@sant0ro yes one moment i'm sorry

**Comment by Killua99x** [comment]
http://prntscr.com/b8geuv

**Comment by Killua99x** [comment]
@sant0ro now you can register
