### ISSUE TITLE
Update to Last Habbo Release

### ISSUE THREAD

**Issue by ovflowd** [sant0ro/Yupi#93]
@TheDoct0r11 we need consider updating to latest Habbo release. I can do that, Cracking the SWF, and Updating the Packets. (But i remember, that some Packets from the Actual Yupi Release are wrong, since the Packets Updater from Xdr, in most scenarios update 99% correct Outgoing Packets and, 80% correct incoming packets)...

Also i need know if you know using AS3 Sorcerer, or Updating Habbo Packets, will be more easiest to explain to you or to get your help, or to update wrong structures.

As far i know the changes between Yupi's SWF release and Habbo.com current release is:
1. Trade Multiplier
2. Convert directly Exchange Furniture into Credits
3. New Habbo Club Page UI
4. Changes in Report Tool
5. Changes in Mod Tools
6. Changes in Help Section
7. Changes in Helper Tool
8. Changes in Avatar Editor
9. Changes in some UI's from some things
10. More?

I need to know if you think is a good idea updating release, or if we only need to do that after Core rewrite and normalize. (Core i mean: Packet System, Composers, Packet Handling, Folder Structure, Socket System, Command Line System, Caching System, Database System, Security System, Logging System). (a lot of these items are actually refactored, or almost refactored, other are far to be done).

Cheers,
Obs.: If we don't do that now, i will close this issue, and reopening when is necessary.

**Comment by TheDoct0r11** [comment]
I don't think we should do that right now as I am rewriting a lot of the core which would introduce a bunch of breaking changes which probably can't be solved by git automatically.

**Comment by ovflowd** [comment]
@TheDoct0r11 yes you're right.
