### ISSUE TITLE
Favorite room and home room button dont work.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#94]
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15548258/e19b1a34-22a7-11e6-831b-b372ff796f70.png)

**Comment by ovflowd** [comment]
If you re-enter the client, the room become favorite? Emulator says any type of error?

**Comment by ghost** [comment]
No, and no error on emulator.

**Comment by BurakDev** [comment]
@sant0ro What about checking if emulator handle packet correctly

**Comment by ovflowd** [comment]
I don't have time now @BurakDev . And also @TheDoct0r11 has no time. 

Our meta is finish the `linux` branch.

But @TheDoct0r11 stopped in the phase of rewrite the message handlers.

**Comment by ghost** [comment]
Just home room button dont work.

**Comment by ovflowd** [comment]
Home room button doesn't work? But this bug is related to `NIO` branch. We re rewriting Yupi, so wait for the Linux branch release. ;)

**Comment by ghost** [comment]
I use BETA Stable version 1.1
https://github.com/sant0ro/Yupi/releases/tag/1.1.0-stable
No Nio branche lol

**Comment by BryanSuero** [comment]
@Anthologique check the packets errors

**Comment by BryanSuero** [comment]
@Anthologique Check the packets errors

**Comment by ghost** [comment]
@BryanSuero How ?

**Comment by ovflowd** [comment]
@Anthologique this build isn't the latest Yupi build. And isn't stable. I will add last build now.

**Comment by ghost** [comment]
@sant0ro Realy ? This is super !

**Comment by ovflowd** [comment]
I forgot to upload the build. Uploading now.
