### ISSUE TITLE
"green_goal, yellow_goal, red_goal and blue_goal" interaction dont work.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#95]
Impossible place a ball on goal.

**Comment by ovflowd** [comment]
Can send Screenies?

**Comment by ghost** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15551587/fd8a188a-22b6-11e6-80e2-da4b820edbc4.png)
The bug is:
Impossible place the ball on goal.

**Comment by ovflowd** [comment]
They are with right interaction at catalogue?

**Comment by ghost** [comment]
Yes, i am no noob lool

**Comment by ovflowd** [comment]
@Anthologique i know that. More respect on issues. They're public ;)

I only will check any Yupi bug in June with @TheDoct0r11, since we're under faculty semester.

**Comment by ovflowd** [comment]
Remembering @Anthologique that these errors are from `NIO` branch, and aren't being supported. Since the current development branch is `LINUX`, also the LINUX branch isn't ready for usage.

We will update LINUX branch starting at June.

**Comment by ghost** [comment]
No, i use only "Yupi Emulator 1.1.0 stable release version".
When You update this version ?
(https://github.com/sant0ro/Yupi/releases/tag/1.1.0-stable)

**Comment by ovflowd** [comment]
As i said The 1.1.0 stable release version is from `NIO` branch.

We're developing the new release in `LINUX` branch, that is far to be done.
