### ISSUE TITLE
Bug with Rares Limited Edition furni

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#96]
When i buy a rares limited edition furniture, and place on my room.
I doble click on furni and the furni dont apear LTD.
![1](https://cloud.githubusercontent.com/assets/6734589/15551095/a5e07b26-22b4-11e6-96bb-8b9d62409ba4.png)
![2](https://cloud.githubusercontent.com/assets/6734589/15551096/a5e3fa6c-22b4-11e6-832a-f202844adc4d.png)
![3](https://cloud.githubusercontent.com/assets/6734589/15551097/a5e5b0be-22b4-11e6-95aa-3dbf92196034.png)

**Comment by ovflowd** [comment]
LTD Furnis is a bug of the Emulator. We didn't finished coding that feature.
