### ISSUE TITLE
Quests dont work.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#97]
When a doble click on quest icon, dont work.
![1](https://cloud.githubusercontent.com/assets/6734589/15551146/ec52396e-22b4-11e6-899a-d88c739c71b0.png)

**Comment by ovflowd** [comment]
Quests are disabled. And all structure from Quests are removed from Yupi. Since Quests is useless.

**Comment by ghost** [comment]
Ok, how remove the icon on the navbar please ?

**Comment by ovflowd** [comment]
External Variables. ;)
