### ISSUE TITLE
Buy events dont apear on navigator.

### ISSUE THREAD

**Issue by ghost** [sant0ro/Yupi#98]
![2](https://cloud.githubusercontent.com/assets/6734589/15551674/5f562068-22b7-11e6-9e38-32659ef547e3.png)
![sans titre](https://cloud.githubusercontent.com/assets/6734589/15551673/5f55007a-22b7-11e6-9c25-d87ff4b8b163.png)

**Comment by ovflowd** [comment]
Because we're rewriting also Navigator.
