### ISSUE TITLE
Whole Yupi SWF pack - with servercamera and furnidata etc

### ISSUE THREAD

**Issue by antrys1223** [sant0ro/Yupi#99]
In the Yupi help thread it says that the its recommended to use the Yupi SWF pack in the release thread. Its not in the release thread anymore only the fixed habbo.swf. I need the furnidata for Yupi emulator so I want the Yupi SWF pack.

Do you have a link?

**Comment by ovflowd** [comment]
No. Someone sent a fake DMCA to Mega.co.nz. I don't have any backup.

**Comment by antrys1223** [comment]
How can I get the emulator working then? ...

**Comment by ovflowd** [comment]
You can use any SWF pack. Only need use the Habbo.swf from the thread.

**Comment by antrys1223** [comment]
No I need the furnidata for the catalogue from Yupi because you can't use another one.

**Comment by ovflowd** [comment]
You can use any furnidata. Or Habbo.com Furnidata.

**Comment by antrys1223** [comment]
Habbo.com Furnidata - Other furnidata don't work either: http://prnt.sc/b8dvmk

**Comment by ovflowd** [comment]
Other Hotels Furnidata have other File Encoding. You need change the encoding ;)

**Comment by antrys1223** [comment]
Do you mean **<?xml version="1.0" encoding="UTF-8"?>**? So yeah to what if I can ask you haha

**Comment by antrys1223** [comment]
UTF-8 is default

**Comment by ovflowd** [comment]
No. Aren't these encodings. Are the "symbols" inside the files. These symbols aren't recognized by C# Built-in XML library.

**Comment by antrys1223** [comment]
How can I fix that then?

**Comment by ovflowd** [comment]
Replacing the symbols that are listed by the Emulator in your XML. Commonly are the symbols with some weird caracters first, like #x9

**Comment by antrys1223** [comment]
How can I see where its listed? Thanks for the help but I just added a furnidata and the only symbols thats its using are < / > " " etc. I know I have to change symbols but I don't get it to be honest. Where are the symbols listed that need to be replaced in the XML file

**Comment by ovflowd** [comment]
These weird symbols are in the text. not in the tags. 
#x9 = ç, as an example.

**Comment by antrys1223** [comment]
Oh thanks! So if I see a word with: sançoro (example) I can just change it with: san#x9oro

**Comment by ovflowd** [comment]
No. is the inverse.

**Comment by antrys1223** [comment]
Only weird symbols I could find are: \* but the furni needs that. Words with ç as example already had ç without the symbol.

**Comment by ovflowd** [comment]
That's really weird.

**Comment by antrys1223** [comment]
I also tried a Azure furnidata just for test purpose but it still says the XML problem.

**Comment by antrys1223** [comment]
Yo. Older version does work with the furnidata's. So its the new emulator 1.1.0 that doesnt work. The Yupi Master does work with it. I'm now gonna test it with AzureWeb

**Comment by antrys1223** [comment]
I can not choose a room with the AzureWEB everything works but not choosing room..

**Comment by ovflowd** [comment]
Yupi Master is an obsolete version and non-recommended version.

**Comment by ovflowd** [comment]
You need use Yupi Habbo.swf

**Comment by antrys1223** [comment]
I used the fixed Yupi SWF

**Comment by antrys1223** [comment]
Gonna try it on firefox now

**Comment by antrys1223** [comment]
Rooms don't work on firefox either.

**Comment by antrys1223** [comment]
client_new

**Comment by antrys1223** [comment]
Do you know how to fix?

**Comment by antrys1223** [comment]
Bro???!!!

**Comment by ovflowd** [comment]
Guy, stop flooding. If you want to use a custom Furnidata, you need fix the special characters.

You didn't said what is the problem, your emulator doesn't start, if not, only change to default Habbo.com furnidata. We will add a todo for universal character set. The `linux` branch already have this fixed. But the `linux` branch isn't ready for usage.

If your client stuck in 76% check the table `server_system_logs` for any errors. Also i commited today the fix for some errors.
